Responsiveness
GreetyCr/Portfolio_Mobil_Firts pull request #4
Opened 2023-06-09 17:24 UTC by GreetyCr

# Responsiveness Update

- Responsiveness in navbar
- Responsiveness in headline
- Responsiveness in works
- Responsiveness in Form

2023-06-09 17:32 UTC, topeogunleye reviewed
Hi @GreetyCr, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request ⚠️

   - You have submitted a project that has failing linters, Kindly make sure your linters are all passing before submitting the PR.

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @topeogunleye in your question so I can receive the notification.


**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

>Invalid Code Review Request **does not count** into the code reviews limit.

2023-06-09 21:11 UTC, frank1738 requested changes
Hi @GreetyCr , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media2.giphy.com/media/hXz6GN0ZilLwhgLo49/giphy.gif"/>


## Highlights

✅ Correct use of Github workflow
✅ No linter error


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

N/A
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-09 21:11 UTC, frank1738 commented on index.html
> +            See project
- [ ] You have done amazing work on your project cards. However, I would suggest that you reduce their width to match the original design and improve their aesthetic aspects. By these, I mean that there should be some spacing around the cards. 

![image](https://github.com/GreetyCr/Portfolio_Mobil_Firts/assets/98453979/2340a15f-07b6-440d-866d-6c2400fd720d)

### Checkout the original design

![image](https://github.com/GreetyCr/Portfolio_Mobil_Firts/assets/98453979/d8adf530-10e2-4f33-a5ae-d23a75d38f5d)

2023-06-09 21:11 UTC, frank1738 commented on index.html
- [ ] The same case also applies to your form section. Kindly reduce its width and position  the `get in touch` button to match the original design

![image](https://github.com/GreetyCr/Portfolio_Mobil_Firts/assets/98453979/f77b4801-7c95-4fa3-b81a-924279a786db)

### Checkout the original design

![image](https://github.com/GreetyCr/Portfolio_Mobil_Firts/assets/98453979/3e0a5a75-ae67-438c-92bb-f9918ea2648d)

2023-06-09 22:02 UTC, ademibowale requested changes
## STATUS: Changes Required :recycle:

### Hi @GreetyCr  , 👋 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media.tenor.com/isiLRnxz3zwAAAAM/cat-driving-serious.gif" width="500px" height="300px">

### To Highlight 🥇

✅ Descriptive Pull Request title and summary. ✔️
✅ Good use of Github flow ✔️
✅All linters are checked.
✅Project is professionally documented.
✅The right GitHub flow method has been used.
✅Professional pull request title and description.

### Changes Required

- [x]  _Please check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me on( @Adebowale ) in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-09 22:18 UTC, GreetyCr commented on styles.css
> +  }
https://github.com/GreetyCr/Portfolio_Mobil_Firts/assets/89504485/277e438a-20d4-42b7-82fb-328091aaeb66

I just tested it in my computer and I dont know how to fix this because I cant see that bug in my repo :( is there other way I can fix this?

2023-06-09 23:03 UTC, jerryowusu requested changes
Hi @GreetyCr 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![so-close](https://github.com/GreetyCr/Portfolio_Mobil_Firts/assets/65233860/1e8283b0-c302-4da2-a838-2fa7e4be1cbc)


 ## Highlights
Great effort so far :heavy_check_mark: 
No linter issues :+1: 

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-09 23:03 UTC, jerryowusu commented on styles.css
> +  }
- [ ] [OPTIONAL] Kindly make sure that the design matches the actual design in terms of all dimensions including the margins, paddings, positions, etc. As shown below, the project card looks smaller and contents spill out at certain screen widths of the desktop version. Kindly check and fix it. 

### Your design 

![Screenshot from 2023-06-09 22-58-17](https://github.com/GreetyCr/Portfolio_Mobil_Firts/assets/65233860/673d2835-54d4-4ab2-8fe6-39bf6449d10f)


### Actual design 


![Screenshot from 2023-06-09 22-58-42](https://github.com/GreetyCr/Portfolio_Mobil_Firts/assets/65233860/3bbc4337-3b66-4b91-a38b-dc82c8625f84)

2023-06-09 23:20 UTC, GreetyCr commented on index.html
> +    <i class="fa-solid fa-bars"></i>
I opened the code in live server and I can't see the hamburguer, si there something I can do so it doesnt happen in other browsers as well?

Thank you in advance for your review and your time


<img width="757" alt="Screenshot 2023-06-09 at 5 19 57 PM" src="https://github.com/GreetyCr/Portfolio_Mobil_Firts/assets/89504485/328cebc5-e775-405c-86f2-0713b4802afa">

2023-06-09 23:43 UTC, GreetyCr commented on index.html
> +    <i class="fa-solid fa-bars"></i>
@jerryowusu (forgot to tag you, sorry)

2023-06-10 00:34 UTC, GreetyCr commented on index.html
> +    <i class="fa-solid fa-bars"></i>
Oh I have a new problem, when I load the page, it appears, but when I save the CSS file, it disappears, and even after the changes,  I reload the page and it still appears

2023-06-10 01:46 UTC, usorfaitheloho approved these changes
Hi @GreetyCr  , 
# STATUS: APPROVED! 🥇 💯 
- [x] Very Nice Design, Keep it up!!
![done](https://media.giphy.com/media/l1uga8ObPBnIBoXUQ/giphy.gif)

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-10 05:27 UTC, merged

2023-06-10 13:23 UTC, jerryowusu commented on index.html
> +    <i class="fa-solid fa-bars"></i>
let's meet in a zoom call if you still have this problem.